### ISSUE TITLE
Install and Update Issue with Mage_OAuth.csv:

### ISSUE THREAD

**Issue by Elfen-Service** [MaWoScha/German_LocalePack_de_DE#1]
WARNING: Target does not exist (.modman/German_LocalePack_de_DE/modman):
 app/locale/de_DE/Mage_OAuth.csv app/locale/de_DE/Mage_OAuth.csv

**Comment by MaWoScha** [comment]
Thank you for reporting!
It is a misspelling:
Change "Mage_OAuth.csv" into "Mage_Oauth.csv"
