### ISSUE TITLE
"Kode"

### ISSUE THREAD

**Issue by kkrieger85** [MaWoScha/German_LocalePack_de_DE#4]
Ich weiß, dass "Kode" die korrekte deutsche Übersetzung von "Code" ist. Allerdings verwirrt das die Bediener mehr als es nützt. 

Daher schlage ich vor, das Auftreten von "Kode" durch "Code" zu ersetzen

**Comment by kkrieger85** [comment]
Gerne auch meine nicht repräsentative Umfrage beachten: https://twitter.com/kkrieger/status/1228223771279945729

**Comment by kkrieger85** [comment]
@MaWoScha Wie kann ich helfen die falsche Übersetzung zu fixen?

**Comment by MaWoScha** [comment]
Ich weiß wirklich nicht, was an "Kode", "kodieren" nicht zu verstehen ist.
All die, die des Deutschen nicht mächtig sind, können ja auf Englisch
umschalten. Dort steht dann "Code". ;-)

**Comment by kkrieger85** [comment]
Es geht um den täglichen Sprachgebrauch. Nicht, ob jemand etwas versteht oder nicht.

Und falls du dich mit Magento auskennst, weißt du, dass wenn man auf Englisch umschaltet, das gesamte BE betroffen ist, nicht nur die Übersetzung "Kode"/"Code"

**Comment by MaWoScha** [comment]
Willst Du mich veralbern? Ohne jetzt nachzusehen behaupte ich mal, dass
"Kode/Code" nur im Backend auftaucht. Und das wird separat von Frontend
einstellt.

**Comment by kkrieger85** [comment]
Warum denkst du, dass ich dich veralbern wolle? 
Kannst du erklären, warum "Kode" überhaupt einzug in die Übersetzung gefunden hat? 

Deine "Nur Backend" Vermutung will ich mit einem Beispiel entkräften: https://github.com/MaWoScha/German_LocalePack_de_DE/blob/a573cbcc1484b454e2d110a455bda8792f629099/app/design/frontend/rwd/default/locale/de_DE/translate.csv#L15

**Comment by MaWoScha** [comment]
Ach, DEN "Code" meinen Sie…
Danke für die Präzisierung.

Welche Variante hätten Sie denn gerne?
Discount
Discount-Code
Ermäßigungscode
Ermäßigungs-Code ...
Gutscheincode
Gutschein-Code
Nachlasscode
Nachlass-Code
Preisnachlasscode
Preisnachlass-Code
Rabattcode
Rabatt-Code

Ich fürchte, das muss man je nach Kundenwunsch individuell anpassen. Da hat
wohl ein jeder seine eigene Präferenz.
Entschuldigung für das "veralbern", ich hatte das nicht genau genug
verstanden.

**Comment by MaWoScha** [comment]
Erledigt!
